### ISSUE TITLE
Create product requirements

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#5]
In order to stay organized and on task, we will need to create a product requirement document.  We may follow the CS305 guidelines for product requirements. 

- Every requirement should be verifiable and traceable
- Every requirement should have:
    - a unique ID
    - a priority to show urgency
    - a status to indicate standing
    - a relationship to other requirements: dependency, grouping, etc.

This issue may be related to issues #3 and #4.

**Comment by baconbm** [comment]
Updated this issue to include more detail (also want to test the connector to teams functionality)

**Comment by afig** [comment]
I agree that following the CS 305 guidelines will result in a high-quality set of product requirements. For M1, we should outline the requirements for a minimum viable product. We can then add on to the requirements as we pick extensions to work on. I am adding this to the M1 milestone so that we address it in a timely manner.

**Comment by afig** [comment]
Will be discussed in-person on Thursday March 7. Any resulting documents will be added to the repo

**Comment by afig** [comment]
Addressed in PR #13
