### ISSUE TITLE
Our github repo needs updated labeling scheme

### ISSUE THREAD

**Issue by baconbm** [smacademic/project-bdf#8]
Currently our github repo has only the default labels, which are adequate but can be improved. 

[This medium article](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63) has some very good ideas. It may be a little too in depth for our project but I think we can still take some inspiration from it.

**Comment by afig** [comment]
The article has some good suggestions, thanks for sharing it @baconbm. I especially like the idea of adding a prefix to labels (e.g. "Type:", "Priority:") to clarify what attribute of an issue it is describing.

I feel that we do not really need to capture *status* in our labels, since our needs are already met by an issue being open/closed, in a milestone/not in a milestone, and assigned/not assigned.

We should probably add labels for *priority*, and refine which *type* categories we want.

For *priority*, I think a simple low, medium, and high will be sufficient. For *type*, I like the wrong/missing/extra categories that are used in DASSL. We could probably also add a non-issue label. What are other's thoughts?

**Comment by baconbm** [comment]
I agree with many of your points @afig 

I would propose for Priority we use -
Priority: High
Priority: Medium
Priority Low

And for type we use -
Type: wrong
Type: missing
Type: extra

Would non-issue fall under 'type'? I don't believe that we will need much complexity beyond these labels.

Another thing (I am taking inspiration from team GEEKS here) - would we want to add a 'code' label for issues pertaining directly to the codebase and perhaps another label such as 'documentation' for issues that do not pertain to the code? Not sure how others feel about this but I thought it was a neat idea.

**Comment by afig** [comment]
Thanks for the list of issue labels. Slightly picky, but I noticed that the categories under Priority start with a capital letter, while the ones for Type start with a lowercase letter. For consistency, I think both should have the same capitalization. I prefer lowercase, but uppercase is just as fine so long as its consistent. 

I think that documentation vs code idea is interesting, but introduces another classification, which would increase the complexity of the labels. I vote no, since it should be clear from the issue title whether it is a documentation or code issue. Thanks for bringing it up.

**Comment by baconbm** [comment]
You are correct, we should have consistent labels, that was an oversight on my part. I agree that we should stick with lowercase. And yes adding another labeling scheme can certainly complicate things too much. 

Should we go with all lowercase? i.e. priority: high vs. Priority: high? I would like to keep the capitalization uniform and have priority and type be lowercase.

**Comment by afig** [comment]
I think we can go with all lowercase, including the attribute name. This will keep it consistent with the default GitHub labels.

When adding the new labels, we should also remove the default labels that GitHub pre-populates.

**Comment by calebeda** [comment]
I like the list of issue labels and I agree that we should go all lowercase

**Comment by afig** [comment]
The new issue labels have now been added and the old default ones removed.
